# Generated by Django 6.0.1 on 2026-02-05 18:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options_cartitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=13, verbose_name='Цена на момент добавления'),
        ),
    ]
